#!/bin/sh

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd "."

# Check if precommit script is defined, skip if not
has_hook_script precommit || exit 0

# Check that npm exists
command_exists npm || {
  echo >&2 "Can't find npm in PATH, skipping precommit script in package.json"
  exit 0
}

# Export Git hook params
export GIT_PARAMS="$*"

# Run npm script
echo "npm run -s precommit (node `node -v`)"
echo

npm run -s precommit || {
  echo
  echo "pre-commit hook failed (add --no-verify to bypass)"
  exit 1
}
